### PR TITLE
Use conda build 3 compilers

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin please rerender

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin please rerender

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin please rerender

**Comment by MatthieuDartiailh** [comment]
The recipe build fine locally. And since it refuses to re-render I do not really know what to do here. @blink1073 would you have an advice on this ?

**Comment by blink1073** [comment]
Maybe the quotes in the build script?  That's the only obvious difference between this and the atom recipe change.  Otherwise, I'd suggest trying a new PR, and if that fails, asking the core maintainers for help.

**Pull request closed without merging**
