### PR TITLE
update recipe for enaml 0.11.0

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
@tacaswell @blink1073 How should I proceed to get the package to be built on Python 3.8 ?

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
@conda-forge-admin, please rerender

**Comment by MatthieuDartiailh** [comment]
There are weird linking issues on Python 3.8 that I do not really follow. Any input appreciated...

**Comment by blink1073** [comment]
It looks like a Python C API function signature changed:

```
import: 'enaml.core.funchelper'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/enaml_1586176740986/test_tmp/run_test.py", line 23, in <module>
    import enaml.signaling
SystemError: bad call flag
```

**Comment by MatthieuDartiailh** [comment]
My bad... Those files are not covered by the tests and I forgot to add tests before the release. I will fix the issue and release a 0.11.1 with the fix.

**Comment by MatthieuDartiailh** [comment]
Actually signaling has been broken since 0.10.1 on Python 3 and nobody ever complained. I will either fix it or just remove the feature seems it does not seem to be used at all. In the meantime it is not worth holding back the conda packages for the release because of that.

**Comment by MatthieuDartiailh** [comment]
@blink1073 does that seems reasonable to you ?

**Comment by blink1073** [comment]
Sounds fair

**Pull request merged**
