### PR TITLE
New version 0.15.0

### PR DESCRIPTION
**Pull request by gabrielcnr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gabrielcnr** [comment]
@marcelotrevisani - thanks for the guidance here

**Comment by gabrielcnr** [comment]
@MatthieuDartiailh it looks like `pip check` is not being able to resolve `atom` 's version... even though in the conda environment we have the requirement fully satisfied as `atom=0.8.0` is there, when `pip check` runs it gets version `0.0.0`... I suspect it may be an issue introduced after changes made to start using `pyproject.toml` fully...

**Comment by marcelotrevisani** [comment]
pip check is not perfect, you can just ignore that and remove that command that is fine, no worries

**Comment by marcelotrevisani** [comment]
@conda-forge-admin please rerender

**Comment by marcelotrevisani** [comment]
enaml now needs ``setuptools_scm`` to build and generate packages that is specified in the pyproject.toml

**Comment by marcelotrevisani** [comment]
probably it will fail because of atom is also missing setuptoosl_scm
if it fails just remove the pip check and please open a PR for atom to also add setuptools_scm at build time

**Pull request merged**
